In [2]:
import numpy as np
a = np.array([[1,2,3]])
b = np.array([[2,3,4],[3,4,5],[4,5,6]])

In [17]:
e = np.concatenate((a.T, b), axis = 1)

In [8]:
3*a+a

array([[ 4,  8, 12]])

In [9]:
c = np.array([1,2,3])

In [15]:
d = np.array([c])

In [24]:
position = [0, 0, 0]
pose = [0.5, -0.5, 0.5, -0.5]

In [26]:
P = np.array([position])
w = pose[0]
q = np.array(pose[1:])
skew = np.array([[0, -q[2], q[1]],
                [q[2], 0, -q[0]],
                [-q[1], q[0], 0]])

In [39]:
w * np.identity(3) + skew

array([[ 0.5,  0.5,  0.5],
       [-0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5]])

In [41]:
E

array([[ 0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5],
       [ 0.5, -0.5, -0.5,  0.5]])

In [42]:
G

array([[ 0.5,  0.5, -0.5, -0.5],
       [-0.5,  0.5,  0.5, -0.5],
       [ 0.5,  0.5,  0.5,  0.5]])

In [44]:
E @ G.T

array([[ 0.,  0.,  1.],
       [-1.,  0.,  0.],
       [ 0., -1.,  0.]])

In [36]:
E = np.concatenate((np.array([-q]).T, w * np.identity(3) + skew), axis = 1)
G = np.concatenate((np.array([-q]).T, w * np.identity(3) - skew), axis = 1)
R = E @ G.T
T = np.concatenate((R, P.T), axis = 1)
T = np.concatenate((T, np.array([[0,0,0,1]])), axis = 0 )

In [37]:
T

array([[ 0.,  0.,  1.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [49]:
objp = np.zeros(( 3*4 , 3), np.float32)
objp.shape

(12, 3)

In [56]:
objp[:,:2] = np.mgrid[0:36:12, 0:48:12].T.reshape(-1,2)
objp

array([[ 0.,  0.,  0.],
       [12.,  0.,  0.],
       [24.,  0.,  0.],
       [ 0., 12.,  0.],
       [12., 12.,  0.],
       [24., 12.,  0.],
       [ 0., 24.,  0.],
       [12., 24.,  0.],
       [24., 24.,  0.],
       [ 0., 36.,  0.],
       [12., 36.,  0.],
       [24., 36.,  0.]], dtype=float32)

In [59]:
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

In [2]:
import cv2
import numpy as np

In [21]:
rvec = np.array([1.0,1.0,1.0],np.float32) 
tvec = np.array([1.0,1.0,1.0],np.float32) 
dst, jacobian = cv2.Rodrigues(rvec)
R = np.array(dst)
T = np.array([tvec])

In [22]:
R

array([[ 0.22629564, -0.18300793,  0.9567123 ],
       [ 0.9567123 ,  0.22629564, -0.18300793],
       [-0.18300793,  0.9567123 ,  0.22629564]], dtype=float32)

In [120]:
def expm(X: np.ndarray):
    val, vec =  np.linalg.eig(X)
    D = vec @ np.diag(np.exp(val))
    res = np.linalg.solve(vec.T, D.T).T
    return res

def logm(X: np.ndarray):
    D, V = np.linalg.eig(X)
    print("eigenval", D, V)
    V_inv = np.linalg.inv(V)
    print("inverse rigvec",V_inv)
    X_tmp = np.diag(np.log(D))
    print(X_tmp)
    logm = V @ X_tmp @ V_inv
    print( V @ X_tmp)
    
    return logm

In [121]:
Y = expm(a)
Y

array([[ 2.71828183e+00,  1.71828183e+00,  1.08616127e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.26424112e+00],
       [ 0.00000000e+00, -3.39934989e-17,  3.67879441e-01]])

In [117]:
logm(Y)

eigenval [2.71828183 1.         0.36787944] [[ 1.         -0.70710678  0.40824829]
 [ 0.          0.70710678 -0.81649658]
 [ 0.          0.          0.40824829]]
inverse rigvec [[1.         1.         1.        ]
 [0.         1.41421356 2.82842712]
 [0.         0.         2.44948974]]
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]
[[ 1.          0.         -0.40824829]
 [ 0.          0.          0.81649658]
 [ 0.          0.         -0.40824829]]


array([[ 1.00000000e+00,  1.00000000e+00, -1.08286639e-15],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.00000000e+00]])

In [118]:
B = np.array([[1,1],[0,1]])

In [119]:
logm(B)

eigenval [1. 1.] [[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]
inverse rigvec [[1.00000000e+00 4.50359963e+15]
 [0.00000000e+00 4.50359963e+15]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


array([[0., 0.],
       [0., 0.]])

In [145]:
v = np.zeros(3*n)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [149]:
m = np.array([np.array([1,2,3])])
I = np.identity(3)
np.array([m, I 0,0,0,1])

SyntaxError: invalid syntax (<ipython-input-149-2f543d633bdd>, line 3)

In [157]:

def logm(X: np.ndarray):
    D, V = np.linalg.eig(X)
    V_inv = np.linalg.inv(V)
    X_tmp = np.diag(np.log(D))
    logm = V @ X_tmp @ V_inv

    return logm

In [158]:
a  = np.array([[ 1,  1,  0],
       [ 0,  0,  2],
       [ 0,  0, -1]])
logm(expm(a))

array([[ 1.00000000e+00,  1.00000000e+00, -1.08286639e-15],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.00000000e+00]])

In [159]:
B = np.array([[1,1],[0,1]])
logm(B)

array([[0., 0.],
       [0., 0.]])

In [171]:
A = np.identity(4)
test = []
t = []
for i in range(3):
    test.append(np.linalg.inv(A[:3,:3]))
    t.append(-A[:3,3])

In [172]:
print(test)

[array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])]


In [173]:
t

[array([-0., -0., -0.]), array([-0., -0., -0.]), array([-0., -0., -0.])]

In [167]:
a,b = [],[]

In [177]:
a = 2* np.identity(3)
np.linalg.norm(a)

3.4641016151377544

In [3]:
objp = np.zeros((3*4 , 1, 3), np.float32)
objp[:,:2] = np.mgrid[0:36:12, 0:48:12].T.reshape(-1,2)

In [5]:
objp.shape

(12, 3)

In [6]:
objp

array([[ 0.,  0.,  0.],
       [12.,  0.,  0.],
       [24.,  0.,  0.],
       [ 0., 12.,  0.],
       [12., 12.,  0.],
       [24., 12.,  0.],
       [ 0., 24.,  0.],
       [12., 24.,  0.],
       [24., 24.,  0.],
       [ 0., 36.,  0.],
       [12., 36.,  0.],
       [24., 36.,  0.]], dtype=float32)

In [22]:
objp = np.zeros((4*3 , 3), np.float32)
objp[:,:2] = np.mgrid[0:3,0:4].T.reshape(-1,2)
objp[:,:2] = (objp[:, :2]+1)*0.012
objp

array([[0.012, 0.012, 0.   ],
       [0.024, 0.012, 0.   ],
       [0.036, 0.012, 0.   ],
       [0.012, 0.024, 0.   ],
       [0.024, 0.024, 0.   ],
       [0.036, 0.024, 0.   ],
       [0.012, 0.036, 0.   ],
       [0.024, 0.036, 0.   ],
       [0.036, 0.036, 0.   ],
       [0.012, 0.048, 0.   ],
       [0.024, 0.048, 0.   ],
       [0.036, 0.048, 0.   ]], dtype=float32)

In [10]:
objp[:,:,:2] = np.mgrid[0:36:12, 0:48:12].T.reshape(-1,2)

(12, 1, 3)

In [43]:
vmax = np.array([1,2,3])
vmin = np.array([0,1,-3])

In [38]:
topface_c = np.array([1.0,1.0,1.0,1.0])
print(topface_c)
np.identity(4) @ topface_c

[1. 1. 1. 1.]


array([1., 1., 1., 1.])

In [33]:
np.concatenate(vmax+vmin, np.array([1]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [44]:
topface_c = np.array([0.0,0.0,0.0,1.0])
topface_c[:3] =  (vmax + vmin)/2
topface_c[3] = vmax[-1] 
print(topface_c)

[0.5 1.5 0.  3. ]


In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [9]:
r = R.from_quat([0, 0, np.sin(np.pi/4), np.cos(np.pi/4)])
print(r)
r.as_dcm()

array([[ 2.22044605e-16, -1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])